### ISSUE TITLE
what would be the best approach with npm but without bower?

### ISSUE THREAD

**Issue by zyro23** [craigburke/grails3-angular2#1]
hi,

just a question - so feel free to close at any time.

when using just npm but not bower what do you think is the best approach handling the `node_modules` directory? i do not think just putting it in `grails-app/assets` does the trick because there are many dependencies which are for development only. not to mention the angular2 worker.dev seems to make `assetCompile` hang completely.

so for now, i ended up putting `node_modules` into my project root and gitignored it. then after a npm install (following the angular 5min getting started guide), i manually copied
- `node_modules/systemjs`
- `node_modules/angular2/bundles` (excluding `web_worker`)

into `grails-app/assets`.

seems to work happy together with your `typescript-asset-pipeline` plugin (with is awesome btw.).

do you see anything that is plain wrong here or that could be simplified? maybe sth. with the gradle nodejs plugin that automatically copies the mentioned files into `grails-app/assets` on `npmInstall`?

would be great to hear/read your feedback/opinion on this.

thank you! zyro

**Comment by craigburke** [comment]
@zyro23 thanks I really appreciate that! There's lots of work to do for the typescript compiler yet (the performance is nowhere near where I want it), but I hope to get back to that soon.

The bower installer plugin is actually pretty flexible and once you configure your dependencies so that it only install what you actually need in your build:
https://github.com/craigburke/bower-installer-gradle

If you want to throw your modified version of this project up on github I'd love to take a look and see what changes I can make on my end.

**Comment by zyro23** [comment]
ok - so you would still say bower is the way to go? after reading https://github.com/angular/angular/issues/4018 i tried to stick with npm only...
